export enum Position {
    DEVELOPER = "DEVELOPER",
    DEVELOPMENT_ANALYST = "DEVELOPMENT_ANALYST",
    ARCHITECT = "ARCHITECT",
    TESTER = "TESTER",
    DEVELOPMENT_LEADER = "DEVELOPMENT_LEADER"
}
